import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/component/toastprovider.component";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en" className={cn("font-sans", geist.variable)}
    >
      <body className="flex min-h-screen flex-col bg-gray-50 text-gray-900">
              <ToastProvider>
                <main className="flex-1 grow">{children}</main>
              </ToastProvider>
      </body>
    </html>
  );
}