import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/component/toastprovider.component";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en" className={roboto.variable}
    >
      <body className="flex min-h-screen flex-col bg-gray-50 text-gray-900">
              <ToastProvider>
                <main className="flex-1 grow">{children}</main>
              </ToastProvider>
      </body>
    </html>
  );
}
